# https://docs.antora.org/antora/latest/antora-container/

FROM antora/antora
RUN yarn global add @antora/lunr-extension

# Run local
# docker build -t local/antora:lunr -f Dockerfile.lunr .
# docker run -v $PWD:/antora --rm -t local/antora:lunr --log-level debug ./mixql-docs/antora-playbook-local.yml

# Run from GitHub
# docker run -v $PWD:/antora --rm -t local/antora:lunr --log-level debug ./mixql-docs/antora-playbook.yml