= What's New in MixQL {page-component-version}
:description: The new features, changes, and bug fixes included in MixQL {page-component-version} and its patch releases.
:doctype: book
:route: New
:url-releases: https://github.com/ntlegion/mixql_docs/releases
:url-git: https://github.com
:url-issues: {url-repo}/issues
:url-milestone-3-2-0: {url-issues}?scope=all&state=closed&label_name%5B%5D=%5BVersion%5D%203.2.0
:url-mr: {url-repo}/merge_requests

== MixQL {page-component-display-version}
_**Release date:** TBD | *Issue label:* {url-milestone-3-2-0}[3.2.0^]_

The primary focus of MixQL {page-component-version} is to provide and refine certain API methods and endpoints to support the development of MixQL extensions.
This release also added syntax for the inclusion and exclusion matching of worktrees and the ability to use the `ref` placeholder in the `edit_url` key.

You can find a summary of the issues resolved in this release below.

=== Resolved issues

==== Added
Issue {url-issues}/535[#535^]:: Allow linked worktree to be used as content source; automatically resolve main repository location and remap HEAD reference in branches.
Issue {url-issues}/1006[#1006^]:: Use value of `versionSegment` property on component version in place of version in output path and URL of pages.
Also, set dynamic `activeVersionSegment` property on component version to indicate which version segment is in use.
Issue {url-issues}/1008[#1008^]:: Add `addSplatAlias` method to `ContentCatalog` for adding a splat (directory) alias.
Issue {url-issues}/1013[#1013^]:: Add support for `ref` placeholder to insert full name of git ref (e.g., `refs/heads/v4.0.x`) in value of `edit_url` key on content source.
Issue {url-issues}/1015[#1015^]::
* Emit `componentsRegistered` event after all components and versions have been registered.
* Store raw files, nav, and startPage data on partially constructed component version until processed.
* Add readable property named `files` to component version in `ContentCatalog#registerComponentVersionStartPage` to get files for component version on access.
* Add readable property named `startPage` to component version in `ContentCatalog#registerComponentVersionStartPage` to look up start page for component version on access.
Issue {url-issues}/1016[#1016^]:: Add syntax to match current branch of specific worktrees in branches pattern (for inclusion or exclusion) (e.g., `HEAD@5.8.x`).
Issue {url-issues}/1021[#1021^]:: Discover implicit site start page in component version promoted to site root.
Content classifier:: Update `ContentCatalog#registerComponentVersionStartPage` to return start page.


==== Changed

Issue {url-issues}/1009[#1009^]:: Remove invalid trailing slash from value of `site.url` when building playbook and from value of `site.url` after `playbookBuilt` event (i.e., when it's provided by an extension).
Issue {url-issues}/1012[#1012^]:: Always assign the value `auth-required` to `origin.private` if the server requests credentials, even when the credentials are embedded in content source URL.
Issue {url-issues}/1026[#1026^]:: Don't recompute resource ID on file from content aggregate if `src.family` is set.
Content classifier:: Shorten `urlSegment` fragment in internal property names on ContentCatalog to `segment` (e.g., `latestVersionUrlSegment` -> `latestVersionSegment`).
Content classifier:: Don't assign fallback value to `url` property on component version if property is already set.
Release process:: Automatically populate additional version and release attributes during release.
Site generator:: Print site URL instead of file URI in completion message if CI=true.

==== Fixed

Issue {url-issues}/1007[#1007^]:: Set `src.version` to original version segment and `src.rel.version` to actual version on splat alias file.
Issue {url-issues}/1010[#1010^]:: Fix infinite authorization loop if credentials embedded in the content source URL are empty and the repository requires authorization.
Issue {url-issues}/1018[#1018^]:: Fix crash if value of `worktrees` key on content source is `~` (`null`) and at least one branch is specified.
Issue {url-issues}/1020[#1020^]:: Add guard to prevent `ContentCatalog#registerSiteStartPage` from registering alias loop.
Issue {url-issues}/1022[#1022^]:: Decouple logic to compute default log format from process environment.
Issue {url-issues}/1024[#1024^]:: Preserve target when creating static route if target is an absolute URL.
Issue {url-issues}/1025[#1025^]:: Allow content aggregator to parse value of `content.branches` and `content.tags` playbook keys.
Playbook builder:: Use consistent formatting for error messages in playbook builder.
Site generator:: Look for IS_TTY on `playbook.env` in site generator to decouple check from process environment.

[#thanks-3-2-0]

== Thank you!

Most important of all, a huge *thank you!* to all the folks who helped make MixQL even better.

